mvp with moxy #1
Ramiz713/RickAndMorty pull request #2
Opened 2019-03-04 20:51 UTC by Ramiz713

![screenshot_2019-03-04-23-48-05-154_com itis2019 rickandmorty](https://user-images.githubusercontent.com/41049352/53762158-66333200-3ed8-11e9-8bcc-2f4962a45e68.png)
![screenshot_2019-03-04-23-48-08-396_com itis2019 rickandmorty](https://user-images.githubusercontent.com/41049352/53762159-66333200-3ed8-11e9-9c54-c3900effb003.png)

2019-03-05 21:04 UTC, NailShaykhrazievItis requested changes

2019-03-05 21:04 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis2019/rickandmorty/characters/CharacterFragment.kt
> +
extra line

2019-03-05 21:04 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis2019/rickandmorty/characters/CharacterFragment.kt
> +        Toast.makeText(activity, message, Toast.LENGTH_SHORT).show()
а то что активити может быть нуллом студия не ругалась
обычно я в лет обарачиваю вызов тоста или снекбара, да и какой тоаст, прошлый век, не материал

2019-03-05 21:04 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis2019/rickandmorty/characters/CharacterPresenter.kt
> +import android.app.Application
android импорт в презентере айайай. В котлине есть аннотация @suppress()
а в конструктор передавай даошку

2019-03-05 21:04 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis2019/rickandmorty/characters/CharacterPresenter.kt
> +    private val apiService = RickAndMortyApiService.create()
Да и лучше спрятать апи и дао под слоем репозитория, ща тут у тебя каша. апи и дао лежат на том же слое что и ui. Открой презенташку по чистой архитектуре или загугли картинку. У тебя более внутренний слой знает о внешнем

2019-03-05 21:04 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis2019/rickandmorty/characters/CharacterPresenter.kt
> +            .subscribe(
subscribeBy более читабельный по мне

2019-03-05 21:04 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis2019/rickandmorty/characters/CharacterPresenter.kt
> +        Completable.fromCallable { charactersList.addAll(characterDao?.getAll() ?: ArrayList()) }
Ты мог в запросе написать onErrorResumeNext и там сходить в бд за данными

2019-03-05 21:04 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis2019/rickandmorty/characters/CharacterView.kt
> +    fun showError(message: String)
А стратегии кто будет писать?

2019-03-05 21:04 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis2019/rickandmorty/model/RickAndMortyApiService.kt
> +    ): Single<LocationList>
Я не сторонник такого код стайла, но он офиц от котлина, так что окей

2019-03-05 21:04 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis2019/rickandmorty/model/character/CharacterDao.kt
> +    @Insert()
А зачем()

2019-03-05 21:04 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/location_item.xml
> +                android:layout_marginTop="8dp"
сtrl alt L в каждом файле

2019-03-06 18:21 UTC, Ramiz713 commented on app/src/main/res/layout/location_item.xml
> +                android:layout_marginTop="8dp"
почему?? я же уже делал...
![image](https://user-images.githubusercontent.com/41049352/53903828-be437300-4055-11e9-9b82-ff94689ebe6a.png)

2019-03-08 17:35 UTC, NailShaykhrazievItis approved these changes

2019-03-08 17:35 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis2019/rickandmorty/Injection.kt
> +object Injection {
красиво

2019-03-09 14:37 UTC, merged